#!/usr/bin/env python3
"""Verify schematic-to-PCB connectivity independent of net names.

The EasyEDA Pro importer gives some autogenerated nets different names in the
schematic and PCB.  The stable identity is therefore the set of
``(reference, pin/pad number)`` endpoints on each connected net.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path

import pcbnew


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def pcb_connectivity(path: Path) -> dict[str, frozenset[tuple[str, str]]]:
    board = pcbnew.LoadBoard(str(path))
    nets: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for footprint in board.GetFootprints():
        reference = footprint.GetReference()
        for pad in footprint.Pads():
            if pad.GetNetCode():
                nets[pad.GetNetname()].add((reference, pad.GetNumber()))
    return {name: frozenset(nodes) for name, nodes in nets.items()}


def schematic_connectivity(path: Path):
    root = ET.parse(path).getroot()
    components = root.findall("./components/comp")
    nets = {}
    for net in root.findall("./nets/net"):
        nodes = frozenset(
            (node.attrib["ref"], node.attrib["pin"]) for node in net.findall("node")
        )
        nets[net.attrib["name"]] = nodes
    return components, nets


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pcb", required=True, type=Path)
    parser.add_argument("--netlist", required=True, type=Path)
    parser.add_argument("--golden-pcb", type=Path)
    parser.add_argument("--json", required=True, type=Path)
    parser.add_argument("--markdown", required=True, type=Path)
    args = parser.parse_args()

    pcb_nets = pcb_connectivity(args.pcb)
    components, schematic_nets = schematic_connectivity(args.netlist)
    connected_schematic_nets = {
        name: nodes for name, nodes in schematic_nets.items() if len(nodes) > 1
    }
    singleton_count = sum(len(nodes) == 1 for nodes in schematic_nets.values())

    schematic_topologies = set(connected_schematic_nets.values())
    exact_matches = {
        name: nodes for name, nodes in pcb_nets.items() if nodes in schematic_topologies
    }
    unmatched_pcb = {
        name: sorted(nodes)
        for name, nodes in pcb_nets.items()
        if nodes not in schematic_topologies
    }
    pcb_hash = sha256(args.pcb)
    golden_hash = sha256(args.golden_pcb) if args.golden_pcb else None

    checks = {
        "schematic_real_components_77": len(components) == 77,
        "schematic_total_nets_102": len(schematic_nets) == 102,
        "schematic_singleton_nets_44": singleton_count == 44,
        "schematic_connected_nets_58": len(connected_schematic_nets) == 58,
        "pcb_nets_58": len(pcb_nets) == 58,
        "all_pcb_nets_exactly_match_schematic_topology": len(exact_matches) == 58,
    }
    if golden_hash is not None:
        checks["working_pcb_byte_identical_to_golden"] = pcb_hash == golden_hash

    result = {
        "inputs": {
            "pcb": str(args.pcb.resolve()),
            "netlist": str(args.netlist.resolve()),
            "golden_pcb": str(args.golden_pcb.resolve()) if args.golden_pcb else None,
        },
        "counts": {
            "schematic_components": len(components),
            "schematic_nets": len(schematic_nets),
            "schematic_singleton_nets": singleton_count,
            "schematic_connected_nets": len(connected_schematic_nets),
            "pcb_nets": len(pcb_nets),
            "exact_topology_matches": len(exact_matches),
            "pcb_net_size_distribution": dict(
                sorted(Counter(map(len, pcb_nets.values())).items())
            ),
        },
        "hashes": {"pcb_sha256": pcb_hash, "golden_pcb_sha256": golden_hash},
        "checks": checks,
        "unmatched_pcb_nets": unmatched_pcb,
        "verdict": "PASS" if all(checks.values()) else "FAIL",
    }

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n")

    rows = "\n".join(
        f"| {'PASS' if passed else 'FAIL'} | `{name}` |" for name, passed in checks.items()
    )
    args.markdown.write_text(
        "# Import Connectivity Gate\n\n"
        f"Verdict: **{result['verdict']}**\n\n"
        "This comparison ignores net names and compares each net by its exact "
        "set of `(reference, pin/pad number)` endpoints.\n\n"
        "| Result | Check |\n|---|---|\n"
        f"{rows}\n\n"
        f"- Schematic: {len(components)} real components, {len(schematic_nets)} total "
        f"nets ({len(connected_schematic_nets)} connected, {singleton_count} singleton).\n"
        f"- PCB: {len(pcb_nets)} nets; exact topology matches: {len(exact_matches)}/{len(pcb_nets)}.\n"
        f"- PCB SHA-256: `{pcb_hash}`.\n"
        "- This gate proves conversion connectivity consistency only; it does not "
        "by itself prove datasheet correctness or production readiness.\n",
        encoding="utf-8",
    )
    print(json.dumps({"verdict": result["verdict"], **result["counts"]}))
    return 0 if result["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
