#pragma once

/* Shared by host descriptor lint and the ESP-IDF/TinyUSB candidate source. */
#define CADENZA_USB_ITF_AUDIO_CONTROL 0
#define CADENZA_USB_ITF_AUDIO_STREAMING_MIC 1
#define CADENZA_USB_ITF_CDC_CONTROL 2
#define CADENZA_USB_ITF_CDC_DATA 3
#define CADENZA_USB_ITF_TOTAL 4

#define CADENZA_USB_EP_AUDIO_IN 0x81
#define CADENZA_USB_EP_CDC_NOTIFICATION 0x82
#define CADENZA_USB_EP_CDC_OUT 0x03
#define CADENZA_USB_EP_CDC_IN 0x83

#define CADENZA_USB_VOICE_SAMPLE_RATE_HZ 48000
#define CADENZA_USB_VOICE_BITS_PER_SAMPLE 16
#define CADENZA_USB_VOICE_CHANNELS 1
#define CADENZA_USB_VOICE_INTERVAL_MS 1
#define CADENZA_USB_VOICE_NOMINAL_PACKET_BYTES 96
#define CADENZA_USB_VOICE_MAX_PACKET_BYTES 98
